export const quote = (value: string) => `'${String(value ?? '').replace(/'/g, "''")}'`;
export const upper = (value?: string, fallback = '') => (value || fallback).trim().toUpperCase();
export const text = (value?: string, fallback = '') => (value || fallback).trim();
export const numberText = (value?: string, fallback = '0') => String(Number(value || fallback) || Number(fallback));
export const gbToMb = (g: number) => Math.round(g * 1024);

export const moduleDefinitions = {
  memory: {
    title: 'Memória',
    description: 'AMM/ASMM, etapa 1, shutdown, startup e conferência.',
    defaults: { totalRam: '16', pct: '50', mode: 'ASMM' },
    fields: [
      { key: 'totalRam', label: 'RAM total (GB)', type: 'number' as const, min: 1 },
      { key: 'pct', label: 'Percentual Oracle (%)', type: 'number' as const, min: 5, max: 90 },
      { key: 'mode', label: 'Modo', type: 'select' as const, options: [
        { label: 'AMM (memory_target)', value: 'AMM' },
        { label: 'ASMM (sga_target + pga_aggregate_target)', value: 'ASMM' },
      ] },
    ],
    templates: [
      { id: 'guide', label: 'Guia de execução', fileName: 'oracle_memory_guide.sql', help: 'Roteiro com ordem de execução.', render: (v: Record<string,string>) => `/* Oracle 19c - Memória (${v.mode || 'ASMM'}) */\n/* Execute na ordem: */\n/* 1) Etapa 1 - parâmetros */\n/* 2) Etapa 2A - shutdown */\n/* 3) Reconecte no banco */\n/* 4) Etapa 2B - startup */\n/* 5) Etapa 3 - conferência */` },
      { id: 'step1', label: 'Etapa 1 - Parâmetros', fileName: 'oracle_memory_parametros.sql', help: 'Grava parâmetros de memória no SPFILE.', render: (v: Record<string,string>) => {
        const ramGb = Number(v.totalRam || 0); const pct = Number(v.pct || 0); const allocMb = gbToMb((ramGb * pct) / 100);
        if (v.mode === 'AMM') { const memMaxTarget = Math.round(allocMb * 1.1); return `/* Etapa 1 - Gravar parâmetros no SPFILE (AMM) */\nALTER SYSTEM SET memory_max_target = ${memMaxTarget}M SCOPE=SPFILE;\nALTER SYSTEM SET memory_target = ${allocMb}M SCOPE=SPFILE;\nALTER SYSTEM SET sga_target = 0 SCOPE=SPFILE;\nALTER SYSTEM SET pga_aggregate_target = 0 SCOPE=SPFILE;`; }
        const sga = Math.round(allocMb * 0.75); const sgaMax = Math.round(sga * 1.1); const pga = Math.round(allocMb * 0.25);
        return `/* Etapa 1 - Gravar parâmetros no SPFILE (ASMM) */\nALTER SYSTEM SET memory_max_target = 0 SCOPE=SPFILE;\nALTER SYSTEM SET memory_target = 0 SCOPE=SPFILE;\nALTER SYSTEM SET sga_max_size = ${sgaMax}M SCOPE=SPFILE;\nALTER SYSTEM SET sga_target = ${sga}M SCOPE=SPFILE;\nALTER SYSTEM SET pga_aggregate_target = ${pga}M SCOPE=SPFILE;`;
      }},
      { id: 'shutdown', label: 'Etapa 2A - Shutdown', fileName: 'oracle_shutdown.sql', help: 'Executado via SQLPlus quando conectado como SYSDBA.', render: () => 'SHUTDOWN IMMEDIATE;' },
      { id: 'startup', label: 'Etapa 2B - Startup', fileName: 'oracle_startup.sql', help: 'Executado via SQLPlus quando conectado como SYSDBA.', render: () => 'STARTUP;' },
      { id: 'check', label: 'Etapa 3 - Conferência', fileName: 'oracle_memory_check.sql', help: 'Confere os parâmetros aplicados.', render: (v: Record<string,string>) => v.mode === 'AMM' ? `/* Etapa 3 - Conferir parâmetros aplicados */\nSELECT name, value, display_value\nFROM v$parameter\nWHERE name IN ('memory_target','memory_max_target','sga_target','pga_aggregate_target')\nORDER BY name;` : `/* Etapa 3 - Conferir parâmetros aplicados */\nSELECT name, value, display_value\nFROM v$parameter\nWHERE name IN ('memory_target','memory_max_target','sga_target','sga_max_size','pga_aggregate_target')\nORDER BY name;` },
    ],
  },

  users: {
    title: 'Usuários', description: 'Criação, remoção, grants, senha, desbloqueio e consultas.',
    defaults: { user: 'ERP', password: 'ERP', tablespace: 'USERS', temp: 'TEMP' },
    fields: [{ key: 'user', label: 'Usuário' }, { key: 'password', label: 'Senha' }, { key: 'tablespace', label: 'Tablespace' }, { key: 'temp', label: 'Temp' }],
    templates: [
      { id: 'create', label: 'Criar usuário completo', fileName: 'create_user_full.sql', help: 'CREATE USER + CONNECT/RESOURCE/DBA + DBMS_CRYPTO + quota unlimited.', render: (v: Record<string,string>) => `/* comandos para criar usuário */\n\n/* ---------------------------------------------------*/\n/* Criando Usuário com Privilégios de DBA */\n/* ---------------------------------------------------*/\nCREATE USER ${upper(v.user,'ERP')} IDENTIFIED BY ${text(v.password,'ERP')}\nDEFAULT TABLESPACE ${upper(v.tablespace,'USERS')}\nTEMPORARY TABLESPACE ${upper(v.temp,'TEMP')}\nPROFILE DEFAULT;\n\n/* ---------------------------------------------------*/\n/* Atribuindo Privilégios aos usuários */\n/* ---------------------------------------------------*/\nGRANT CONNECT, RESOURCE, DBA TO ${upper(v.user,'ERP')};\n\nGRANT EXECUTE ON SYS.DBMS_CRYPTO TO ${upper(v.user,'ERP')};\n\nALTER USER ${upper(v.user,'ERP')} QUOTA UNLIMITED ON ${upper(v.tablespace,'USERS')};` },
      { id: 'drop_only', label: 'Somente DROP USER', fileName: 'drop_user.sql', help: 'Somente o comando DROP USER.', render: (v: Record<string,string>) => `/* comandos para remover usuário */\nDROP USER ${upper(v.user,'ERP')} CASCADE;` },
      { id: 'create_only', label: 'Somente CREATE USER', fileName: 'create_user.sql', help: 'Cria usuário sem grants.', render: (v: Record<string,string>) => `/* Criando Usuário */\nCREATE USER ${upper(v.user,'ERP')} IDENTIFIED BY ${text(v.password,'ERP')}\nDEFAULT TABLESPACE ${upper(v.tablespace,'USERS')}\nTEMPORARY TABLESPACE ${upper(v.temp,'TEMP')}\nPROFILE DEFAULT;` },
      { id: 'grant_only', label: 'Somente grants e quota', fileName: 'grant_user_privs.sql', help: 'Grants e quota para usuário existente.', render: (v: Record<string,string>) => `/* Atribuindo Privilégios aos usuários */\nGRANT CONNECT, RESOURCE, DBA TO ${upper(v.user,'ERP')};\n\nGRANT EXECUTE ON SYS.DBMS_CRYPTO TO ${upper(v.user,'ERP')};\n\nALTER USER ${upper(v.user,'ERP')} QUOTA UNLIMITED ON ${upper(v.tablespace,'USERS')};` },
      { id: 'reset', label: 'Resetar senha', fileName: 'reset_password.sql', help: 'Redefine a senha.', render: (v: Record<string,string>) => `ALTER USER ${upper(v.user,'ERP')} IDENTIFIED BY ${text(v.password,'ERP')};` },
      { id: 'unlock', label: 'Desbloquear usuário', fileName: 'unlock_user.sql', help: 'Desbloqueia conta e consulta status.', render: (v: Record<string,string>) => `ALTER USER ${upper(v.user,'ERP')} IDENTIFIED BY ${text(v.password,'ERP')} ACCOUNT UNLOCK;\n\nSELECT username, account_status, expiry_date\nFROM dba_users\nWHERE username = ${quote(upper(v.user,'ERP'))};` },
      { id: 'expire', label: 'Expirar senha', fileName: 'expire_user.sql', help: 'Força troca de senha no próximo login.', render: (v: Record<string,string>) => `ALTER USER ${upper(v.user,'ERP')} PASSWORD EXPIRE;` },
      { id: 'list', label: 'Listar usuários', fileName: 'list_users.sql', help: 'Lista usuários com status e tablespace padrão.', render: () => `SELECT username, account_status, default_tablespace, temporary_tablespace, profile\nFROM dba_users\nORDER BY username;` },
      { id: 'privs', label: 'Ver privilégios do usuário', fileName: 'user_privileges.sql', help: 'Consulta roles e privilégios do usuário.', render: (v: Record<string,string>) => `SELECT *\nFROM dba_role_privs\nWHERE grantee = ${quote(upper(v.user,'ERP'))}\nORDER BY granted_role;\n\nSELECT *\nFROM dba_sys_privs\nWHERE grantee = ${quote(upper(v.user,'ERP'))}\nORDER BY privilege;` },
    ],
  },

  tablespaces: {
    title: 'Tablespaces', description: 'Modelos de tablespace e datafile.',
    defaults: { tablespace: 'USERS', filePath: 'E:\\app\\Administrador\\oradata\\orcl\\USERS09.DBF', size: '6', next: '2', owner: 'ERP' },
    fields: [{ key: 'tablespace', label: 'Tablespace' }, { key: 'filePath', label: 'Arquivo DBF' }, { key: 'size', label: 'Tamanho (GB)', type: 'number' as const }, { key: 'next', label: 'NEXT (GB)', type: 'number' as const }, { key: 'owner', label: 'Owner' }],
    templates: [
      { id:'users_list', label:'USERS — listar datafiles', fileName:'users_list_datafiles.sql', help:'Lista datafiles da tablespace informada.', render:(v:Record<string,string>)=>`SELECT F.FILE_ID,\n       F.FILE_NAME,\n       F.TABLESPACE_NAME,\n       ROUND(F.BYTES/1048576) AS SIZE_MB,\n       ROUND(F.USER_BYTES/1048576) AS USER_MB,\n       F.BLOCKS,\n       F.AUTOEXTENSIBLE,\n       F.INCREMENT_BY,\n       ROUND(F.MAXBYTES/1048576) AS MAXSIZE_MB\nFROM DBA_DATA_FILES F\nWHERE F.TABLESPACE_NAME = ${quote(upper(v.tablespace,'USERS'))}\nORDER BY F.FILE_ID;`},
      { id:'users_metrics', label:'USERS — métricas', fileName:'users_tablespace_metrics.sql', help:'Mostra métricas da tablespace.', render:(v:Record<string,string>)=>`SELECT T.TABLESPACE_NAME,\n       T.USED_SPACE,\n       T.TABLESPACE_SIZE,\n       T.USED_PERCENT\nFROM DBA_TABLESPACE_USAGE_METRICS T\nWHERE T.TABLESPACE_NAME = ${quote(upper(v.tablespace,'USERS'))};`},
      { id:'users_expand', label:'USERS — adicionar datafile', fileName:'users_expand_datafile.sql', help:'Adiciona datafile com autoextend.', render:(v:Record<string,string>)=>`ALTER TABLESPACE ${upper(v.tablespace,'USERS')} ADD DATAFILE ${quote(text(v.filePath))} SIZE ${numberText(v.size,'6')}G AUTOEXTEND ON NEXT ${numberText(v.next,'2')}G MAXSIZE UNLIMITED;`},
      { id:'create_ts', label:'Criar tablespace', fileName:'create_tablespace.sql', help:'Cria tablespace nova com autoextend.', render:(v:Record<string,string>)=>`CREATE TABLESPACE ${upper(v.tablespace,'USERS')}\nDATAFILE ${quote(text(v.filePath))} SIZE ${numberText(v.size,'6')}G\nAUTOEXTEND ON NEXT ${numberText(v.next,'2')}G MAXSIZE UNLIMITED\nEXTENT MANAGEMENT LOCAL\nSEGMENT SPACE MANAGEMENT AUTO;\n\nSELECT tablespace_name, status, contents\nFROM dba_tablespaces\nWHERE tablespace_name = ${quote(upper(v.tablespace,'USERS'))};`},
      { id:'list_ts', label:'Listar tablespaces / datafiles', fileName:'list_tablespaces.sql', help:'Lista datafiles e tablespaces.', render:()=>`SELECT tablespace_name, file_name, bytes/1024/1024 AS mb, autoextensible\nFROM dba_data_files\nORDER BY tablespace_name, file_name;`},
      { id:'free_space', label:'Espaço livre por tablespace', fileName:'free_space.sql', help:'Mostra espaço livre por tablespace.', render:()=>`SELECT df.tablespace_name,\n       ROUND(SUM(df.bytes)/1024/1024) AS total_mb,\n       ROUND(SUM(NVL(fs.bytes,0))/1024/1024) AS free_mb,\n       ROUND((SUM(df.bytes)-SUM(NVL(fs.bytes,0)))/1024/1024) AS used_mb\nFROM dba_data_files df\nLEFT JOIN dba_free_space fs ON df.tablespace_name = fs.tablespace_name\nGROUP BY df.tablespace_name\nORDER BY 1;`},
      { id:'big_objects', label:'Maiores objetos', fileName:'largest_objects.sql', help:'Lista maiores objetos do owner informado.', render:(v:Record<string,string>)=>`SELECT owner, segment_name, segment_type, bytes/1024/1024 AS mb\nFROM dba_segments\nWHERE owner = ${quote(upper(v.owner,'ERP'))}\nORDER BY bytes DESC\nFETCH FIRST 30 ROWS ONLY;`},
      { id:'nearly_full', label:'Tablespaces quase cheias', fileName:'tablespaces_nearly_full.sql', help:'Tablespaces com utilização alta.', render:()=>`SELECT tablespace_name, used_percent, tablespace_size, used_space\nFROM dba_tablespace_usage_metrics\nWHERE used_percent >= 85\nORDER BY used_percent DESC;`},
    ],
  },

  datafiles: {
    title: 'Expandir Datafiles', description: 'Pacote completo e comandos individuais para datafiles.',
    defaults: { usersFile: 'D:\\APP\\ADMINISTRADOR\\ORADATA\\ORCL\\USERS01.DBF', usersSize:'30', usersNext:'1', tempFile:'D:\\APP\\ADMINISTRADOR\\ORADATA\\ORCL\\TEMP01.DBF', tempSize:'1', tempNext:'256', systemFile:'D:\\APP\\ADMINISTRADOR\\ORADATA\\ORCL\\SYSTEM01.DBF', systemSize:'6', systemNext:'1', openCursors:'2000', processes:'600' },
    fields: [{key:'usersFile',label:'USERS01.DBF'}, {key:'usersSize',label:'USERS size GB',type:'number' as const}, {key:'usersNext',label:'USERS next GB',type:'number' as const}, {key:'tempFile',label:'TEMP01.DBF'}, {key:'tempSize',label:'TEMP size GB',type:'number' as const}, {key:'tempNext',label:'TEMP next MB',type:'number' as const}, {key:'systemFile',label:'SYSTEM01.DBF'}, {key:'systemSize',label:'SYSTEM size GB',type:'number' as const}, {key:'systemNext',label:'SYSTEM next GB',type:'number' as const}, {key:'openCursors',label:'open_cursors',type:'number' as const}, {key:'processes',label:'processes',type:'number' as const}],
    templates: [
      {id:'full',label:'Pacote completo',fileName:'expandir_datafiles_pack.sql',help:'Parâmetros + perfil + resize/autoextend USERS, TEMP e SYSTEM.',render:(v:Record<string,string>)=>`ALTER SYSTEM SET deferred_segment_creation=FALSE;\nALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;\nALTER SYSTEM SET open_cursors=${numberText(v.openCursors,'2000')} SCOPE=SPFILE;\nALTER SYSTEM SET processes=${numberText(v.processes,'600')} SCOPE=SPFILE;\n\nALTER DATABASE DATAFILE ${quote(text(v.usersFile))} RESIZE ${numberText(v.usersSize,'30')}G;\nALTER DATABASE DATAFILE ${quote(text(v.usersFile))} AUTOEXTEND ON NEXT ${numberText(v.usersNext,'1')}G MAXSIZE UNLIMITED;\n\nALTER DATABASE TEMPFILE ${quote(text(v.tempFile))} RESIZE ${numberText(v.tempSize,'1')}G;\nALTER DATABASE TEMPFILE ${quote(text(v.tempFile))} AUTOEXTEND ON NEXT ${numberText(v.tempNext,'256')}M MAXSIZE UNLIMITED;\n\nALTER DATABASE DATAFILE ${quote(text(v.systemFile))} RESIZE ${numberText(v.systemSize,'6')}G;\nALTER DATABASE DATAFILE ${quote(text(v.systemFile))} AUTOEXTEND ON NEXT ${numberText(v.systemNext,'1')}G MAXSIZE UNLIMITED;`},
      {id:'params',label:'Somente parâmetros',fileName:'expandir_datafiles_parametros.sql',help:'Somente parâmetros e PASSWORD_LIFE_TIME.',render:(v:Record<string,string>)=>`ALTER SYSTEM SET deferred_segment_creation=FALSE;\nALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;\nALTER SYSTEM SET open_cursors=${numberText(v.openCursors,'2000')} SCOPE=SPFILE;\nALTER SYSTEM SET processes=${numberText(v.processes,'600')} SCOPE=SPFILE;`},
      {id:'users',label:'USERS01.DBF',fileName:'expandir_users01.sql',help:'Resize e autoextend USERS.',render:(v:Record<string,string>)=>`ALTER DATABASE DATAFILE ${quote(text(v.usersFile))} RESIZE ${numberText(v.usersSize,'30')}G;\nALTER DATABASE DATAFILE ${quote(text(v.usersFile))} AUTOEXTEND ON NEXT ${numberText(v.usersNext,'1')}G MAXSIZE UNLIMITED;`},
      {id:'temp',label:'TEMP01.DBF',fileName:'expandir_temp01.sql',help:'Resize e autoextend TEMP.',render:(v:Record<string,string>)=>`ALTER DATABASE TEMPFILE ${quote(text(v.tempFile))} RESIZE ${numberText(v.tempSize,'1')}G;\nALTER DATABASE TEMPFILE ${quote(text(v.tempFile))} AUTOEXTEND ON NEXT ${numberText(v.tempNext,'256')}M MAXSIZE UNLIMITED;`},
      {id:'system',label:'SYSTEM01.DBF',fileName:'expandir_system01.sql',help:'Resize e autoextend SYSTEM.',render:(v:Record<string,string>)=>`ALTER DATABASE DATAFILE ${quote(text(v.systemFile))} RESIZE ${numberText(v.systemSize,'6')}G;\nALTER DATABASE DATAFILE ${quote(text(v.systemFile))} AUTOEXTEND ON NEXT ${numberText(v.systemNext,'1')}G MAXSIZE UNLIMITED;`},
    ],
  },

  importExport: {
    title: 'Import/Export', description: 'Data Pump, directories, jobs e histórico RMAN.',
    defaults: { dir:'DATA_PUMP_DIR', path:'E:\\backup\\oracle', admin:'system', pass:'oracle', service:'orclpdb', source:'ERP_', target:'ERP_BASE', dump:'ERP_BASE.DMP', log:'ERP_BASE.LOG', parallel:'8' },
    fields: [{key:'dir',label:'Directory'}, {key:'path',label:'Caminho físico'}, {key:'admin',label:'Usuário admin'}, {key:'pass',label:'Senha'}, {key:'service',label:'Service'}, {key:'source',label:'Schema origem'}, {key:'target',label:'Schema destino'}, {key:'dump',label:'Dump'}, {key:'log',label:'Log'}, {key:'parallel',label:'Parallel',type:'number' as const}],
    templates: [
      {id:'dir_list',label:'Listar directories',fileName:'list_directories.sql',help:'Lista diretórios Oracle.',render:()=>`SELECT *\nFROM dba_directories\nORDER BY directory_name;`},
      {id:'dir_create',label:'Criar directory',fileName:'create_directory.sql',help:'Cria diretório e concede READ/WRITE.',render:(v:Record<string,string>)=>`CREATE OR REPLACE DIRECTORY ${upper(v.dir,'DATA_PUMP_DIR')} AS ${quote(text(v.path,'E:\\backup\\oracle'))};\nGRANT READ, WRITE ON DIRECTORY ${upper(v.dir,'DATA_PUMP_DIR')} TO ${upper(v.target,'ERP_BASE')};\n\nSELECT *\nFROM dba_directories\nWHERE directory_name = ${quote(upper(v.dir,'DATA_PUMP_DIR'))};`},
      {id:'impdp',label:'Gerar IMPDP',fileName:'import_impdp.txt',help:'Comando de terminal para importação com REMAP_SCHEMA.',render:(v:Record<string,string>)=>`IMPDP ${text(v.admin,'system')}/${text(v.pass,'oracle')}@${text(v.service,'orclpdb')} PARALLEL=${numberText(v.parallel,'8')} DUMPFILE=${text(v.dump,'ERP_BASE.DMP')} LOGFILE=${text(v.log,'ERP_BASE.LOG')} SCHEMAS=(${upper(v.source,'ERP_')}) REMAP_SCHEMA=(${upper(v.source,'ERP_')}:${upper(v.target,'ERP_BASE')}) DIRECTORY=${upper(v.dir,'DATA_PUMP_DIR')}`},
      {id:'expdp',label:'Gerar EXPDP',fileName:'export_expdp.txt',help:'Comando de terminal para exportação.',render:(v:Record<string,string>)=>`EXPDP ${text(v.admin,'system')}/${text(v.pass,'oracle')}@${text(v.service,'orclpdb')} SCHEMAS=(${upper(v.target,'ERP_BASE')}) DUMPFILE=${upper(v.target,'ERP_BASE')}.DMP LOGFILE=${upper(v.target,'ERP_BASE')}.LOG CONSISTENT=Y REUSE_DUMPFILES=Y DIRECTORY=${upper(v.dir,'DATA_PUMP_DIR')}`},
      {id:'jobs',label:'Ver jobs Data Pump',fileName:'datapump_jobs.sql',help:'Consulta jobs do Data Pump.',render:()=>`SELECT owner_name, job_name, operation, job_mode, state, attached_sessions\nFROM dba_datapump_jobs\nORDER BY owner_name, job_name;`},
      {id:'rman',label:'Histórico RMAN',fileName:'rman_history.sql',help:'Histórico de jobs RMAN.',render:()=>`SELECT start_time, end_time, status, input_type, output_device_type\nFROM v$rman_backup_job_details\nORDER BY start_time DESC;`},
    ],
  },

  sessions: {
    title:'Sessões e Locks', description:'Sessões ativas, bloqueios, locks, kill session e inativas.', defaults:{sid:'123',serial:'4567',user:'ERP'},
    fields:[{key:'sid',label:'SID',type:'number' as const},{key:'serial',label:'SERIAL#',type:'number' as const},{key:'user',label:'Usuário'}],
    templates:[
      {id:'active',label:'Sessões ativas',fileName:'active_sessions.sql',help:'Lista sessões ativas.',render:()=>`SELECT sid, serial#, username, status, machine, program, event\nFROM v$session\nWHERE status = 'ACTIVE'\nORDER BY username, sid;`},
      {id:'blocking',label:'Sessões bloqueando',fileName:'blocking_sessions.sql',help:'Mostra sessões bloqueando outras.',render:()=>`SELECT blocking_session, sid, serial#, username, event\nFROM v$session\nWHERE blocking_session IS NOT NULL\nORDER BY blocking_session, sid;`},
      {id:'locks',label:'Locks atuais',fileName:'locks.sql',help:'Locks atuais por sessão/objeto.',render:()=>`SELECT s.sid, s.serial#, s.username, o.object_name, l.type, l.lmode, l.request\nFROM v$lock l\nJOIN v$session s ON l.sid = s.sid\nLEFT JOIN dba_objects o ON l.id1 = o.object_id\nORDER BY s.sid;`},
      {id:'kill',label:'Gerar kill session',fileName:'kill_session.sql',help:'Gera comando para matar sessão.',render:(v:Record<string,string>)=>`ALTER SYSTEM KILL SESSION '${numberText(v.sid,'123')},${numberText(v.serial,'4567')}' IMMEDIATE;`},
      {id:'inactive',label:'Sessões inativas',fileName:'inactive_sessions.sql',help:'Sessões inativas do usuário informado.',render:(v:Record<string,string>)=>`SELECT sid, serial#, username, status, machine, logon_time\nFROM v$session\nWHERE status = 'INACTIVE'\n  AND username = ${quote(upper(v.user,'ERP'))}\nORDER BY logon_time;`},
    ],
  },

  diagnostic: {
    title:'Diagnóstico', description:'Health check, inválidos, recompilação, tamanho e parâmetros.', defaults:{owner:'ERP', env:'ERP Produção'},
    fields:[{key:'owner',label:'Owner'}, {key:'env',label:'Ambiente'}],
    templates:[
      {id:'health',label:'Health check geral',fileName:'health_check.sql',help:'Health check geral em pacote único.',render:(v:Record<string,string>)=>`/* Health Check - ${text(v.env,'ERP Produção')} */\nSELECT name, open_mode, log_mode FROM v$database;\nSELECT instance_name, host_name, version, status FROM v$instance;\nSELECT tablespace_name, used_percent FROM dba_tablespace_usage_metrics ORDER BY used_percent DESC;\nSELECT owner, object_type, object_name FROM dba_objects WHERE status = 'INVALID' ORDER BY owner, object_type;\nSELECT sid, serial#, username, status FROM v$session WHERE status = 'ACTIVE' ORDER BY username;\nSELECT name, value FROM v$parameter WHERE name IN ('memory_target','memory_max_target','sga_target','sga_max_size','pga_aggregate_target') ORDER BY name;\nSELECT * FROM dba_directories ORDER BY directory_name;`},
      {id:'invalid',label:'Objetos inválidos',fileName:'invalid_objects.sql',help:'Objetos inválidos do owner informado.',render:(v:Record<string,string>)=>`SELECT owner, object_type, object_name, status\nFROM dba_objects\nWHERE status = 'INVALID'\n  AND owner = ${quote(upper(v.owner,'ERP'))}\nORDER BY object_type, object_name;`},
      {id:'recompile',label:'Recompilar inválidos',fileName:'recompile_invalid.sql',help:'Recompilação serial dos objetos inválidos.',render:()=>`EXEC UTL_RECOMP.RECOMP_SERIAL();`},
      {id:'dbsize',label:'Tamanho total do banco',fileName:'database_size.sql',help:'Tamanho total do banco.',render:()=>`SELECT ROUND(SUM(bytes)/1024/1024/1024,2) AS size_gb\nFROM dba_data_files;`},
      {id:'schemasize',label:'Maiores schemas',fileName:'schema_sizes.sql',help:'Maiores schemas do banco.',render:()=>`SELECT owner, ROUND(SUM(bytes)/1024/1024,2) AS mb\nFROM dba_segments\nGROUP BY owner\nORDER BY mb DESC;`},
      {id:'params',label:'Parâmetros principais',fileName:'main_parameters.sql',help:'Parâmetros principais do banco.',render:()=>`SHOW PARAMETER memory;\nSHOW PARAMETER sga;\nSHOW PARAMETER pga;\n\nSELECT name, value\nFROM v$parameter\nWHERE name IN ('db_name','db_unique_name','service_names','open_cursors','processes')\nORDER BY name;`},
    ],
  },

  erp: {
    title:'ERP Presets', description:'Setup inicial, implantação, pós-importação e checklist.', defaults:{user:'ERP_HIDRAUMAQ', tablespace:'USERS', source:'ERP_', target:'ERP_BASE', oraPath:'E:\\Oracle19\\App\\Oracle\\oradata\\ORCL19', password:'ERP'},
    fields:[{key:'user',label:'Usuário ERP'}, {key:'password',label:'Senha'}, {key:'tablespace',label:'Tablespace'}, {key:'source',label:'Schema origem'}, {key:'target',label:'Schema destino'}, {key:'oraPath',label:'Pasta oradata'}],
    templates:[
      {id:'setupinicial',label:'Setup Inicial do Banco',fileName:'erp_setup_inicial.sql',help:'Setup inicial completo do banco.',render:(v:Record<string,string>)=>{const u=upper(v.user,'ERP'), ts=upper(v.tablespace,'USERS'), p=text(v.password,'ERP'), ora=text(v.oraPath,'E:\\Oracle19\\App\\Oracle\\oradata\\ORCL19'); return `/* ============================================================\n   SETUP INICIAL DO BANCO ORACLE 19c\n   Usuário: ${u} | Tablespace: ${ts}\n   ============================================================ */\n\n-- 1. Criar usuário ERP\nCREATE USER ${u} IDENTIFIED BY ${p}\nDEFAULT TABLESPACE ${ts}\nTEMPORARY TABLESPACE TEMP\nPROFILE DEFAULT;\n\nGRANT CONNECT, RESOURCE, DBA TO ${u};\nGRANT EXECUTE ON SYS.DBMS_CRYPTO TO ${u};\n\nALTER USER ${u} QUOTA UNLIMITED ON ${ts};\n\n-- 2. Expandir Tablespace USERS (adicionar datafiles)\nALTER TABLESPACE ${ts} ADD DATAFILE '${ora}\\${ts}02.DBF'\n  SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;\n\nALTER TABLESPACE ${ts} ADD DATAFILE '${ora}\\${ts}03.DBF'\n  SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;\n\nALTER TABLESPACE ${ts} ADD DATAFILE '${ora}\\${ts}04.DBF'\n  SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;\n\nALTER TABLESPACE ${ts} ADD DATAFILE '${ora}\\${ts}05.DBF'\n  SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;\n\n-- 3. Parâmetros de sistema\nALTER SYSTEM SET deferred_segment_creation=FALSE;\nALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;\nALTER SYSTEM SET open_cursors=2000 SCOPE=SPFILE;\nALTER SYSTEM SET processes=600 SCOPE=SPFILE;\n\n-- 4. Redimensionar datafile USERS01\nALTER DATABASE DATAFILE '${ora}\\${ts}01.DBF' RESIZE 30G;\nALTER DATABASE DATAFILE '${ora}\\${ts}01.DBF'\n  AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;\n\n-- 5. Ajustar TEMP\nALTER DATABASE TEMPFILE '${ora}\\TEMP01.DBF' RESIZE 1G;\nALTER DATABASE TEMPFILE '${ora}\\TEMP01.DBF'\n  AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED;\n\n-- 6. Ajustar SYSTEM\nALTER DATABASE DATAFILE '${ora}\\SYSTEM01.DBF' RESIZE 6G;\nALTER DATABASE DATAFILE '${ora}\\SYSTEM01.DBF'\n  AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;\n\n-- ============================================================\n\n-- ============================================================`; }},
      {id:'install',label:'Pacote de implantação ERP',fileName:'erp_install_pack.sql',help:'Pacote base de implantação ERP.',render:(v:Record<string,string>)=>`/* Implantação ERP */\nDROP USER ${upper(v.user,'ERP_HIDRAUMAQ')} CASCADE;\nCREATE USER ${upper(v.user,'ERP_HIDRAUMAQ')} IDENTIFIED BY ${upper(v.user,'ERP_HIDRAUMAQ')}\nDEFAULT TABLESPACE ${upper(v.tablespace,'USERS')}\nTEMPORARY TABLESPACE TEMP\nPROFILE DEFAULT;\nGRANT CONNECT, RESOURCE, DBA TO ${upper(v.user,'ERP_HIDRAUMAQ')};\nGRANT EXECUTE ON SYS.DBMS_CRYPTO TO ${upper(v.user,'ERP_HIDRAUMAQ')};\nALTER USER ${upper(v.user,'ERP_HIDRAUMAQ')} QUOTA UNLIMITED ON ${upper(v.tablespace,'USERS')};\n\nSELECT * FROM DBA_DIRECTORIES WHERE DIRECTORY_NAME = 'DATA_PUMP_DIR';\n\n-- Importação exemplo\nIMPDP system/oracle@orclpdb PARALLEL=8 DUMPFILE=${upper(v.target,'ERP_BASE')}.DMP LOGFILE=${upper(v.target,'ERP_BASE')}.LOG SCHEMAS=(${upper(v.source,'ERP_')}) REMAP_SCHEMA=(${upper(v.source,'ERP_')}:${upper(v.target,'ERP_BASE')}) DIRECTORY=DATA_PUMP_DIR;`},
      {id:'postimport',label:'Checklist pós-importação',fileName:'erp_post_import_check.sql',help:'Checklist pós-importação.',render:(v:Record<string,string>)=>`/* Pós-importação ERP */\nSELECT username, account_status FROM dba_users WHERE username = ${quote(upper(v.user,'ERP_HIDRAUMAQ'))};\nSELECT * FROM dba_role_privs WHERE grantee = ${quote(upper(v.user,'ERP_HIDRAUMAQ'))};\nSELECT * FROM dba_objects WHERE owner = ${quote(upper(v.target,'ERP_BASE'))} AND status = 'INVALID';\nSELECT * FROM dba_directories WHERE DIRECTORY_NAME = 'DATA_PUMP_DIR';\nSELECT tablespace_name, used_percent FROM dba_tablespace_usage_metrics ORDER BY used_percent DESC;\nSELECT name, value FROM v$parameter WHERE name IN ('service_names','open_cursors');`},
      {id:'crypto',label:'Grant DBMS_CRYPTO',fileName:'grant_crypto.sql',help:'Grant específico de DBMS_CRYPTO.',render:(v:Record<string,string>)=>`GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ${upper(v.user,'ERP_HIDRAUMAQ')};`},
      {id:'healthpack',label:'Pacote de diagnóstico ERP',fileName:'erp_health_pack.sql',help:'Pacote rápido de diagnóstico para suporte ERP.',render:(v:Record<string,string>)=>`SELECT instance_name, version, status FROM v$instance;\nSELECT sid, serial#, username, status, machine FROM v$session WHERE status='ACTIVE' ORDER BY username;\nSELECT tablespace_name, used_percent FROM dba_tablespace_usage_metrics ORDER BY used_percent DESC;\nSELECT owner, object_type, object_name FROM dba_objects WHERE status='INVALID' AND owner = ${quote(upper(v.target,'ERP_BASE'))};\nSELECT start_time, status, input_type FROM v$rman_backup_job_details ORDER BY start_time DESC;`},
      {id:'checklist',label:'Checklist técnico',fileName:'erp_checklist.txt',help:'Checklist operacional/técnico.',render:(v:Record<string,string>)=>`[ ] Oracle instalado\n[ ] Listener respondendo\n[ ] Service name validado\n[ ] Usuário ERP criado\n[ ] Tablespace ${upper(v.tablespace,'USERS')} pronta\n[ ] DATA_PUMP_DIR validado\n[ ] Importação executada\n[ ] Objetos inválidos recompilados\n[ ] DBMS_CRYPTO concedido\n[ ] Backup/RMAN validado\n[ ] Health check final executado`},
    ],
  },
};
